apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: system
spec:
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.20
    helm:
      values: |
        replicaCount: 1
  # destination:
  #   server: 'https://kubernetes.default.svc'
  #   namespace: system
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true