apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: system
spec:
  project: default
  source:
    chart: podinfo
    repoURL: "https://stefanprodan.github.io/podinfo"
    targetRevision: "6.3.2"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true