apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: system
spec:
  project: default
  source:
    chart: trivy-operator
    repoURL: https://aquasecurity.github.io/helm-charts/
    targetRevision: 0.24.1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: system
    createNamespace: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true