apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tyk
  namespace: argocd
spec:
  project: default
  source:
    chart: tyk
    repoURL: https://helm.tyk.io/public/helm/charts/
    targetRevision: 0.18.0
    helm:
      values: |
        replicaCount: 1
        
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true