apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-applicationset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: 'https://github.com/amine7777/wp-k8s-kustomize.git'
      revision: HEAD
      directories:
      - path: app-of-apps/overlays/dev
  template:
    metadata:
      name: 'mami-applications'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/amine7777/wp-k8s-kustomize.git'
        targetRevision: HEAD
        path: app-of-apps/overlays/dev
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
