apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-applicationset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - cluster: appofapps1
            url: 'https://kubernetes.default.svc'
            repoURL: 'https://github.com/amine7777/wp-k8s-kustomize.git'
            revision: HEAD
            project: default
            directories:
              - app-of-apps/overlays/dev

          - cluster: appofapps2
            url: 'https://kubernetes.default.svc'
            repoURL: 'https://github.com/amine7777/wp-k8s-kustomize.git'
            revision: HEAD
            project: default
            directories:
              - app-of-apps/overlays/prod
  template:
    metadata:
      name: '{{ .cluster }}-appy'
    spec:
      project: "{{ .project }}"
      source:
        repoURL: "{{ .repoURL }}"
        targetRevision: "{{ .revision }}"
        path: "{{ index .directories 0 }}"
      destination:
        server: "{{ .url }}"
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

