apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: main-oleole
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    # - git:
    #   repoURL: 'https://github.com/amine7777/wp-k8s-kustomize.git'
    #   revision: HEAD
    #   directories:
    #   - path: clusters/zoo/oleole/*

    - list:
        elements:
          - app: external-secrets
            tenant: zoo
            env: oleole
            url: 'https://kubernetes.default.svc'
            chart: external-secrets
            repoURL: "https://charts.external-secrets.io"
            targetRevision: 0.9.20
            project: core
            namespace: system

          - app: argocd
            tenant: zoo
            env: oleole
            url: 'https://kubernetes.default.svc'
            chart: argo-cd
            repoURL: 'https://argoproj.github.io/argo-helm'
            targetRevision: 7.3.11
            project: core
            namespace: argocd

          - app: cert-manager
            tenant: zoo
            env: oleole
            url: 'https://kubernetes.default.svc'
            chart: cert-manager
            repoURL: 'https://charts.jetstack.io'
            targetRevision: 1.15.1
            project: core
            namespace: system

          - app: tyk
            tenant: zoo
            env: oleole
            url: 'https://kubernetes.default.svc'
            chart: tyk-operator
            repoURL: https://helm.tyk.io/public/helm/charts/
            targetRevision: 0.18.10
            project: core
            namespace: system
  template:
    metadata:
      name: "{{ .app }}"

    spec:
      project: core
      sources:

        - repoURL: 'https://github.com/amine7777/wp-k8s-kustomize.git'
          targetRevision: HEAD
          path: "clusters/{{ .tenant }}/{{ .env }}"
          ref: values
    
        - repoURL: "{{ .repoURL }}"
          chart: "{{ .chart }}"
          targetRevision: "{{ .targetRevision }}"
          helm:
            valueFiles:
              - '$values/{{ .app }}.yml'
      destination:
        server: "{{ .url }}"
        namespace: "{{ .namespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - ServerSideApply=true
        retry:
          limit: 7
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
