apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core
  namespace: argocd
spec:
  description: Development Project OleOle - test 
  sourceRepos:
    - 'https://github.com/amine7777/wp-k8s-kustomize.git'
    - 'https://argoproj.github.io/argo-helm'
    - 'https://charts.jetstack.io'
    - 'https://charts.external-secrets.io'
    - 'https://stefanprodan.github.io/podinfo'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'


  roles:
  - name: read-only
    description: Read-only privileges to core project
    policies:
    - p, proj:core:read-only, applications, get, core/*, allow
    groups:
    - my-oidc-group
