
# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: main
#   namespace: argocd
# spec:
#   goTemplate: true
#   goTemplateOptions: ["missingkey=default"]
#   generators:
#   - matrix:
#       generators:
#       - git:
#           repoURL: 'https://github.com/amine7777/wp-k8s-kustomize.git'
#           revision: HEAD
#           files:
#           - path: clusters/zoo/oleole/argo-config/elements.yml
#       - list:
#           elementsYaml: "{{ .key.components | toJson }}"      
#   template:
#     metadata:
#       name: '{{.app}}'
#     spec:
#       project: '{{.project}}'
#       sources:
#         - repoURL: 'https://github.com/amine7777/wp-k8s-kustomize.git'
#           targetRevision: HEAD
#           ref: values
    
#         - repoURL: '{{.repoURL}}'
#           chart: '{{.chart}}'
#           targetRevision: '{{.targetRevision}}'
#           path: '{{.gitPath:}}'
#           helm:
#             valueFiles:
#               - '$values/{{.valuesPath}}'
#       destination:
#         server: '{{.url}}'
#         namespace: '{{.namespace}}'
#       syncPolicy:
#         automated:
#           prune: true
#           selfHeal: true
#         syncOptions:
#           - CreateNamespace=true
#           - PrunePropagationPolicy=foreground
#           - PruneLast=true
#           - ServerSideApply=true
#         retry:
#           limit: 7
#           backoff:
#             duration: 10s
#             factor: 2
#             maxDuration: 3m



apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: main
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=default"]
  generators:
    - list:
        elements: 
          - app: argocd
            url: 'https://kubernetes.default.svc'
            chart: argo-cd
            repoURL: 'https://argoproj.github.io/argo-helm'
            targetRevision: 7.3.11
            project: core
            namespace: argocd
            valueFiles: 
              - '$values/clusters/zoo/oleole/values/argocd.yml'

          - app: podinfo
            url: 'https://kubernetes.default.svc'
            repoURL: 'https://github.com/amine7777/wp-k8s-kustomize.git'
            targetRevision: HEAD
            path: 'apps/bases/podinfo'
            project: core
            namespace: argocd

          - app: cert-manager
            url: 'https://kubernetes.default.svc'
            chart: cert-manager
            repoURL: 'https://charts.jetstack.io'
            targetRevision: 1.15.1
            project: core
            namespace: system
            valueFiles: 
              - '$values/clusters/zoo/oleole/values/cert-manager.yml'

          - app: mysql
            url: 'https://kubernetes.default.svc'
            repoURL: 'https://github.com/amine7777/wp-k8s-kustomize.git'
            targetRevision: master
            project: core
            namespace: system
            path: apps/bases/mysql  
  template:
    metadata:
      name: '{{.app}}'
    spec:
      project: '{{.project}}'
      sources: []
      destination:
        server: '{{.url}}'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - ServerSideApply=true
        retry:
          limit: 7
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m

  templatePatch: |
    spec:
      sources:
        - repoURL: 'https://github.com/amine7777/wp-k8s-kustomize.git'
          targetRevision: HEAD
          ref: values

        - repoURL: '{{.repoURL}}'
          targetRevision: '{{.targetRevision}}'
        {{- if .path }}
          path: '{{.path}}'
        {{- end }}
        {{- if .chart }}
          chart: '{{.chart}}'
          helm:
            valueFiles:
            {{- range $valueFile := .valueFiles }}
              - {{ $valueFile }}
            {{- end }}
        {{- end }}

  


