apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: main
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=default"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: 'https://github.com/amine7777/wp-k8s-kustomize.git'
          revision: HEAD
          files:
          - path: 'clusters/zoo/oleole/argo-config/elements.yml'
      - list:
          elementsYaml: "{{ .key.components | toJson }}" 

  template:
    metadata:
      name: '{{.app}}'
    spec:
      project: '{{.project}}'
      sources: []
      destination:
        server: '{{.url}}'
        namespace: '{{.namespace}}'
      syncPolicy: {}
  templatePatch: |
    spec:
      sources:
        - repoURL: 'https://github.com/amine7777/wp-k8s-kustomize.git'
          targetRevision: HEAD
          ref: values

        - repoURL: '{{.repoURL}}'
          targetRevision: '{{.targetRevision}}'
        {{- if .gitPath }}
          path: '{{.gitPath}}'
        {{- end }}
        {{- if .chart }}
          chart: '{{.chart}}'
          helm:
            valueFiles:
            {{- range $valueFile := .valueFiles }}
              - {{ $valueFile }}
            {{- end }}
        {{- end }}
      syncPolicy:
        automated:
          prune: {{ .syncPolicy.automated.prune | default true }}
          selfHeal: {{ .syncPolicy.automated.selfHeal | default true }}
        syncOptions:
          {{- range $option := $syncOptions }}
          - {{ $option }}
          {{- end }}
        retry:
          limit: {{ .syncPolicy.retry.limit | default 10 }}
          backoff:
            duration: {{ .syncPolicy.retry.backoff.duration | default "10s" }}
            factor: {{ .syncPolicy.retry.backoff.factor | default 2 }}
            maxDuration: {{ .syncPolicy.retry.backoff.maxDuration | default "3m" }}
    

  


