
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: main
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: 'https://github.com/amine7777/wp-k8s-kustomize.git'
          revision: HEAD
          files:
          - path: clusters/zoo/oleole/argo-config/elements.yml
      - list:
          elementsYaml: "{{ .key.components | toJson }}"      
  template:
    metadata:
      name: '{{.app}}'
    spec:
      project: '{{.project}}'
      sources:
        - repoURL: 'https://github.com/amine7777/wp-k8s-kustomize.git'
          targetRevision: HEAD
          ref: values
    
        - repoURL: '{{.repoURL}}'
          chart: '{{.chart}}'
          targetRevision: '{{.targetRevision}}'
          path: '{{.gitPath:}}'
          helm:
            valueFiles:
              - '$values/{{.valuesPath}}'
      destination:
        server: '{{.url}}'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - ServerSideApply=true
        retry:
          limit: 7
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m