apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: system
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.15.1
    helm:
      values: |
        replicaCount: 1
        crds:
          enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: system
    createNamespace: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

