apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: my-app-ns
spec:
  project: default
  source:
    repoURL: 'https://github.com/amine7777/wp-k8s-kustomize.git'
    targetRevision: HEAD
    path: apps/overlays/dev
  destination:
    server: 'https://cluster.default.svc'
    namespace: my-app-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
