apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-community
  namespace: argocd
spec:
  project: default
  source:
    chart: prometheus-community
    repoURL: https://prometheus-community.github.io/helm-charts/
    targetRevision: 25.24.1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true